name: Publish Node.js Package @ddd-master/*

on:
  release:
    types: [published]

jobs:
  publish-npm:
    runs-on: ubuntu-latest

    steps:
      - name: Setup checkout actions
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install turbo
        run: npm i turbo-linux-64

      - name: Install dependencies
        run: npm ci

      - name: Build all libs
        run: npm run build:all
        
      - name: Publish all libs
        run: npm run publish:all
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
